services:
  - type: web
    name: youtube-downloader
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: youtube-temp
      mountPath: /opt/render/project/src/temp
      sizeGB: 1